### ISSUE TITLE
Idea: rotary encoder and segmented display?

### ISSUE THREAD

**Issue by petermolnar** [smartboxchannel/SONOFF-SNZB-02-Temperature-and-humidity-sensor#1]
I have no idea if it's possible or not, but I'm curious if you see a way to add a rotary encoder, a selector button, and a display to turn the snzb-02 into a fully funtioning room thermostat on it's own.

**Comment by w-strive** [comment]
When I compile the IAR project, I always find an error message indicating that the python environment is properly installed

**Comment by smartboxchannel** [comment]
I think it's possible, maybe with blue tape and hot glue :), but it will be a monster :).

**Comment by w-strive** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by smartboxchannel** [comment]
:)

сб, 26 нояб. 2022 г. в 14:26, 小w ***@***.***>:
