### ISSUE TITLE
keep reset switch from falling off while removing and replacing the board from the case

### ISSUE THREAD

**Issue by patman-cp** [smartboxchannel/SONOFF-SNZB-02-Temperature-and-humidity-sensor#2]
How did you keep the tiny reset switch in place when dissassembling and reassembling everything?

Or do you not care, given the new firmware can behave however you want.

I got one where it had already fallen off, I could not reset it, and thought it was broken. I opened it up, and the switch had fallen off and was in the case.

I opened a working one and figured out where and how it attaches, but ended up knocking its switch loose too when putting it back together.

On both, with difficulty I can place and hold the switch, put the inner case on, add the battery, click it and get it to work. But the switch just falls off after that - there is nothing to hold it in place. I won't be able to reset them again without disassembling and repeating the process.

In hindsight, I could probably open a working one and leave the PCB in the outer case without touching the switch, but pulling the whole thing out and inserting it again looks like it'll just pull the switch off.

**Comment by smartboxchannel** [comment]
Hello, Oh, how I understand you :). It looks like this is a disease, my button has also fallen off 2 times already, and on one there the switching membrane inside the button broke, I had to solder another button. You need to insert the board back very carefully, you need to pay attention to the moment that the button is inserted under the plastic cover of the button.

**Comment by patman-cp** [comment]
I don't see how that switch can take any force perpendicular to how it's mounted unless it's glued to the board. I think I'll try gluing it (using 5 minute epoxy or super glue) next try - one of my two with broken switches is not responding, so I have to take it apart again to reset it.

I think the contact points are on the edges where the solder spots are, or less likely on the two indents where it plugs in - manually shorting those should work to reset it (rather than trying to hold the switch in place and press it at the same time), I tried but can't tell if I was shorting it or not as the contacts are so tiny.
